nginx:
  build: docker/nginx
  ports:
    - "8080:80"
  links:
    - php
    - mysql
  volumes:
    - ./:/app 
php:
  build: docker/php
  volumes:
    - ./:/app
  links:
    - mysql
  working_dir: /app

mysql:
  image: mysql:latest
  expose:
    - "3306"
  ports:
   - "3307:3306"
  environment:
    MYSQL_DATABASE: nfq_test
    MYSQL_USER: root
    MYSQL_PASSWORD: y8JXuSnDGue52wVM
    MYSQL_ROOT_PASSWORD: mYmtBJEDj76NhtbB
    PMA_HOST: mysql