security:
    encoders:
        AppBundle\Entity\Admin:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle:Admin
                property: username

    firewalls:
        main:
            anonymous: ~
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_ADMIN }
